name_dict = {
    "John Doe": "A software engineer from San Francisco.",
    "Jane Smith": "A doctor specializing in pediatric medicine.",
    "Alice Johnson": "A professor of computer science.",
    "Bob Brown": "An artist who loves painting landscapes.",
    "Charlie Davis": "A mechanical engineer working in the automotive industry.",
    "Diana Evans": "A marketing manager at a tech startup.",
    "Ethan Foster": "A high school teacher who teaches mathematics.",
    "Fiona Green": "A chef who specializes in Italian cuisine.",
    "George Harris": "A financial analyst with a passion for stock markets.",
    "Hannah Ingram": "A journalist covering international news.",
    "Ian Jackson": "A photographer known for his wildlife photography.",
    "Jill King": "An environmental scientist studying climate change.",
    "Kevin Lewis": "A musician who plays the piano and guitar.",
    "Laura Miller": "A novelist who writes historical fiction.",
    "Michael Nelson": "An architect with a focus on sustainable design.",
    "Nina Olson": "A veterinarian who works with exotic animals.",
    "Oscar Perez": "A graphic designer specializing in branding.",
    "Paula Quinn": "A lawyer focusing on corporate law.",
    "Quentin Reed": "A pilot who flies commercial airplanes.",
    "Rachel Scott": "A yoga instructor with a background in dance.",
    "Samuel Turner": "A software developer working on web applications.",
    "Tina Underwood": "A biochemist researching new medicines.",
    "Ulysses Vance": "An entrepreneur who started his own tech company.",
    "Victoria White": "A fashion designer known for her minimalist style.",
    "William Xander": "A historian who studies ancient civilizations.",
    "Xena Young": "An actress with a love for theater.",
    "Yvonne Zimmerman": "A linguist who speaks five languages.",
    "Zachary Adams": "A personal trainer specializing in weight loss.",
    "Amanda Baker": "A dentist who owns her own practice.",
    "Brian Carter": "A firefighter with 10 years of experience.",
    "Catherine Diaz": "A social worker helping children in need.",
    "David Edwards": "A civil engineer working on infrastructure projects.",
    "Erin Fisher": "A business consultant with expertise in finance.",
    "Frank Garcia": "A chef known for his fusion cuisine.",
    "Grace Howard": "An illustrator who creates children's books.",
    "Henry Irving": "A cybersecurity expert working in the public sector.",
    "Isabella Jenkins": "A real estate agent with a focus on luxury properties.",
    "Jack Kelly": "A retired police officer now volunteering in his community.",
    "Katherine Lee": "A choreographer working in the film industry.",
    "Liam Martinez": "A marine biologist studying coral reefs.",
    "Mia Nolan": "An economist analyzing global market trends.",
    "Nathan Owens": "A software engineer with a passion for AI.",
    "Olivia Parker": "A wedding planner with a creative flair.",
    "Patrick Quinn": "A professor of philosophy at a local university.",
    "Rebecca Russell": "A nutritionist helping people achieve their health goals.",
    "Steve Taylor": "A graphic novelist and comic book writer.",
    "Tracy Upton": "A documentary filmmaker focusing on social issues.",
    "Uma Vasquez": "A pediatric nurse with 15 years of experience.",
    "Victor Wilson": "A computer scientist researching quantum computing.",
    "Wendy Xu": "A financial advisor specializing in retirement planning.",
    "Xander Young": "A cinematographer with a passion for storytelling.",
    "Yasmine Zane": "A playwright with a love for experimental theater.",
    "Aaron Blake": "A political analyst working for a news network.",
    "Beth Cooper": "An event planner specializing in corporate events.",
    "Carl Duncan": "A software architect designing scalable systems.",
    "Dana Ellison": "A behavioral therapist helping people with anxiety.",
    "Elliot Ford": "A content creator focusing on tech reviews.",
    "Felicia Grant": "A nurse practitioner working in family medicine.",
    "Gavin Hughes": "A data scientist with a focus on machine learning.",
    "Hazel Irving": "An art curator at a contemporary art gallery.",
    "Isaac Jones": "A digital marketer helping brands grow online.",
    "Julia King": "A librarian with a passion for rare books.",
    "Kyle Lawrence": "A sports coach specializing in basketball.",
    "Lena Morris": "An urban planner working on sustainable city designs.",
    "Mason Norris": "A video game developer creating indie games.",
    "Nora Owens": "A social media manager for a fashion brand.",
    "Owen Peters": "A product manager at a tech startup.",
    "Piper Quinn": "A speech therapist working with children.",
    "Quincy Riley": "A geologist studying earthquakes and tectonics.",
    "Rita Sanders": "A museum director with a focus on history exhibits.",
    "Simon Thomas": "A patent attorney with expertise in technology.",
    "Tara Underhill": "A personal stylist for high-profile clients.",
    "Umar Vega": "A supply chain manager at a manufacturing company.",
    "Violet Walsh": "A landscape architect designing public parks.",
    "Wade Xanders": "A cybersecurity consultant for small businesses.",
    "Ximena Yates": "A dancer and choreographer for a dance company.",
    "Yuri Zimmerman": "A software tester ensuring quality in mobile apps.",
    "Zane Anderson": "A mechanical engineer with a passion for robotics.",
    "Abby Barnes": "A nutrition coach focusing on plant-based diets.",
    "Blake Carter": "A digital artist creating fantasy illustrations.",
    "Chloe Diaz": "A clinical psychologist specializing in trauma therapy.",
    "Derek Ellis": "A structural engineer working on skyscrapers.",
    "Ella Fisher": "A marine conservationist protecting ocean wildlife.",
    "Finn Garcia": "A cinematographer with a love for documentary film.",
    "Gina Howard": "A personal assistant to a high-profile executive.",
    "Harvey Irving": "A software developer with a focus on mobile apps.",
    "Ivy Johnson": "A graphic designer with a passion for typography.",
    "Jackie Kelly": "A life coach helping people achieve their goals.",
    "Kurt Lawson": "A civil rights attorney fighting for justice.",
    "Lilly Moore": "A pastry chef known for her creative desserts.",
    "Milo Nelson": "A game designer with a passion for virtual reality.",
    "Nina Owens": "A journalist covering technology news.",
    "Omar Patel": "A business strategist with expertise in e-commerce.",
    "Paige Quinn": "A public relations specialist for tech companies.",
    "Quinn Rivera": "A professor of political science at a major university.",
    "Ralph Smith": "A project manager in the construction industry.",
    "Sophie Taylor": "A travel blogger exploring the world.",
    "Tom Underwood": "A software engineer specializing in cloud computing.",
    "Uma Vincent": "A professor of English literature.",
    "Vincent White": "A mechanical engineer with a focus on renewable energy."
}
